services:
  - type: web
    name: pmc-rag-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: pmc_rag
      - key: MONGODB_COLLECTION
        value: article_chunks
      - key: MONGODB_INDEX_NAME
        value: vector_index
      - key: EMBEDDING_MODEL_NAME
        value: NeuML/pubmedbert-base-embeddings
      - key: GROQ_API_KEY
        sync: false
      - key: LLM_MODEL
        value: openai/gpt-oss-120b
      - key: TOP_K
        value: "5"
      - key: PMC_TOPIC_QUERY
        value: Neurology and Psychiatry
      - key: PMC_MAX_ARTICLES
        value: "800"
      - key: NCBI_API_EMAIL
        sync: false
